package backend.spring.modelos;

public enum MarcaMoto {
    APRILIA,BENELLI,BIMOTA,BMW,DUCATI,GASGAS,HARLEY_DABIDSON,HONDA,KAWASAKI,KTM,SUZUKI,YAMAHA,VOGE,ZONTES,ZERO,VESPA,TRIUMPH,BRIXTON,CAN_AM,CF_MOTO,DAELIM,DERBI,ENERGICA,FANTIC,HANWAY,HUSQVARNA,HYOSUNG,INDIAN,KEEWAY,HYMCO,LAMBRELLA,MACBOR,MALAGUTI,MASH,MH,MITT,MONDIAL,MONTESA,MOTO_GUZZI,MOTO_MORINI,MV_AGUSTA,NIU,PEUGEOT,PIAGGIO,QOODER,RIEJU,ROYAL_ENFIELD,SCRAMBLER_DUCATI,SILENCE,SWM,SYM
}
