-- Datos generados automáticamente con nombres de tabla correctos

INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 81', 210.27, 'Descripción de ejemplo 85', 'img_2.jpg', 2, 3, 'Azul', false, 1, 2);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 96', 178.05, 'Descripción de ejemplo 33', 'img_4.jpg', 2, 5, 'Verde', true, 1, 2);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 88', 39.13, 'Descripción de ejemplo 19', 'img_2.jpg', 4, 5, 'Verde', true, 1, 3);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 26', 491.53, 'Descripción de ejemplo 11', 'img_3.jpg', 4, 2, 'Gris', false, 4, 2);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 46', 92.3, 'Descripción de ejemplo 52', 'img_3.jpg', 5, 4, 'Verde', false, 4, 5);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 43', 448.8, 'Descripción de ejemplo 96', 'img_10.jpg', 1, 1, 'Azul', true, 4, 5);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 30', 485.93, 'Descripción de ejemplo 89', 'img_9.jpg', 3, 1, 'Gris', false, 3, 5);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 42', 306.75, 'Descripción de ejemplo 58', 'img_6.jpg', 1, 4, 'Azul', true, 2, 5);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 43', 282.0, 'Descripción de ejemplo 56', 'img_5.jpg', 3, 4, 'Gris', false, 4, 4);
INSERT INTO cascomoto (nombre, precio, descripcion, imagen_url, talla, tipo_casco, color, homologado, material, marca_casco) VALUES ('Nombre 20', 180.9, 'Descripción de ejemplo 87', 'img_7.jpg', 5, 2, 'Rojo', true, 1, 2);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 3', 'Descripción de ejemplo 24', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 53', 'Descripción de ejemplo 46', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 62', 'Descripción de ejemplo 21', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 87', 'Descripción de ejemplo 57', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 98', 'Descripción de ejemplo 29', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 36', 'Descripción de ejemplo 48', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 35', 'Descripción de ejemplo 14', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 20', 'Descripción de ejemplo 44', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 74', 'Descripción de ejemplo 72', NULL);
INSERT INTO categoria (nombre_categoria, descripcion, categoria_padre_id) VALUES ('Nombre 89', 'Descripción de ejemplo 36', NULL);
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 62', 1, 26.9, 'Descripción de ejemplo 37', 'img_1.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 33', 5, 399.9, 'Descripción de ejemplo 28', 'img_10.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 58', 5, 152.53, 'Descripción de ejemplo 90', 'img_2.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 14', 3, 85.57, 'Descripción de ejemplo 38', 'img_9.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 17', 1, 54.37, 'Descripción de ejemplo 7', 'img_9.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 68', 4, 117.58, 'Descripción de ejemplo 86', 'img_7.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 19', 5, 40.41, 'Descripción de ejemplo 32', 'img_3.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 72', 3, 306.09, 'Descripción de ejemplo 78', 'img_10.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 5', 3, 455.46, 'Descripción de ejemplo 51', 'img_7.jpg');
INSERT INTO componentemoto (nombre, marca_moto, precio, descripcion, imagen_url) VALUES ('Nombre 96', 1, 117.36, 'Descripción de ejemplo 10', 'img_3.jpg');
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 62', 71.32, 'Descripción de ejemplo 87', 'img_2.jpg', 3, 2);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 57', 486.12, 'Descripción de ejemplo 56', 'img_2.jpg', 4, 2);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 16', 152.83, 'Descripción de ejemplo 13', 'img_7.jpg', 1, 1);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 55', 413.79, 'Descripción de ejemplo 43', 'img_9.jpg', 3, 1);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 78', 312.53, 'Descripción de ejemplo 27', 'img_6.jpg', 2, 4);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 5', 353.11, 'Descripción de ejemplo 21', 'img_10.jpg', 1, 1);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 59', 490.59, 'Descripción de ejemplo 44', 'img_5.jpg', 3, 1);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 98', 143.33, 'Descripción de ejemplo 42', 'img_9.jpg', 3, 5);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 53', 329.64, 'Descripción de ejemplo 71', 'img_6.jpg', 3, 4);
INSERT INTO guantesmoto (nombre, precio, descripcion, imagen_url, talla, material) VALUES ('Nombre 23', 401.58, 'Descripción de ejemplo 50', 'img_10.jpg', 3, 3);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (421.63, 1, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (162.08, 1, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (210.5, 2, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (109.57, 3, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (133.99, 3, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (398.34, 3, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (229.61, 3, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (51.53, 1, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (168.95, 5, NULL);
INSERT INTO lineapedido (precio, cantidad, pedido_id) VALUES (66.73, 4, NULL);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 98', 247.13, 'Descripción de ejemplo 100', 'img_8.jpg', 4, 5, NULL, '2021-09-12', 28);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 97', 107.32, 'Descripción de ejemplo 50', 'img_10.jpg', 1, 1, NULL, '2021-04-02', 151);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 98', 344.46, 'Descripción de ejemplo 37', 'img_6.jpg', 2, 5, NULL, '2023-02-13', 106);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 36', 298.32, 'Descripción de ejemplo 39', 'img_5.jpg', 2, 5, NULL, '2020-01-10', 60);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 66', 462.85, 'Descripción de ejemplo 78', 'img_9.jpg', 3, 5, NULL, '2021-10-08', 121);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 80', 325.75, 'Descripción de ejemplo 41', 'img_5.jpg', 1, 5, NULL, '2025-01-06', 141);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 1', 434.15, 'Descripción de ejemplo 37', 'img_8.jpg', 3, 2, NULL, '2022-12-25', 152);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 6', 316.17, 'Descripción de ejemplo 69', 'img_9.jpg', 1, 5, NULL, '2024-08-14', 68);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 39', 27.72, 'Descripción de ejemplo 29', 'img_8.jpg', 1, 2, NULL, '2024-02-12', 184);
INSERT INTO moto (nombre, precio, descripcion, imagen_url, tipo_moto, marca_moto, modelo, anno_fabricacion, cv) VALUES ('Nombre 45', 444.63, 'Descripción de ejemplo 11', 'img_2.jpg', 4, 5, NULL, '2023-02-03', 190);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2020-12-29', 'Texto 12', 809.37, 337.95, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2021-08-03', 'Texto 25', 583.87, 237.4, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2021-04-21', 'Texto 49', 914.37, 396.33, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2021-06-14', 'Texto 4', 305.19, 574.91, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2021-02-25', 'Texto 2', 352.82, 766.02, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2020-08-16', 'Texto 28', 616.43, 869.5, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2023-03-24', 'Texto 99', 416.76, 429.58, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2022-11-25', 'Texto 95', 478.0, 674.06, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2019-12-28', 'Texto 26', 696.0, 641.87, NULL, NULL, NULL);
INSERT INTO pedido (fecha, observaciones, descuento, total, cliente_id, estado_pedido, operario_id) VALUES ('2023-09-06', 'Texto 56', 827.03, 602.04, NULL, NULL, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (2, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (2, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (2, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (2, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO rolusuario (rol, usuario_id) VALUES (1, NULL);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 8', 70.03, 'Descripción de ejemplo 27', 'img_2.jpg', 5, 4, 'Verde', 5);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 66', 57.31, 'Descripción de ejemplo 74', 'img_6.jpg', 1, 3, 'Rojo', 2);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 31', 483.03, 'Descripción de ejemplo 86', 'img_3.jpg', 5, 1, 'Verde', 3);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 49', 40.21, 'Descripción de ejemplo 3', 'img_3.jpg', 4, 1, 'Azul', 3);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 85', 325.45, 'Descripción de ejemplo 26', 'img_8.jpg', 3, 2, 'Negro', 3);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 43', 354.65, 'Descripción de ejemplo 11', 'img_9.jpg', 5, 1, 'Azul', 5);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 60', 259.58, 'Descripción de ejemplo 8', 'img_3.jpg', 5, 5, 'Gris', 5);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 75', 363.38, 'Descripción de ejemplo 2', 'img_2.jpg', 1, 3, 'Negro', 3);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 1', 221.03, 'Descripción de ejemplo 91', 'img_6.jpg', 2, 5, 'Gris', 5);
INSERT INTO trajemoto (nombre, precio, descripcion, imagen_url, marca_traje, tallas_traje, color, material) VALUES ('Nombre 21', 253.6, 'Descripción de ejemplo 76', 'img_4.jpg', 4, 1, 'Gris', 2);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 71', 'Texto 46', 'user91@example.com', 'user_351', '627634704', 'pass5884', false);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 34', 'Texto 36', 'user41@example.com', 'user_231', '634786553', 'pass3840', false);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 87', 'Texto 100', 'user46@example.com', 'user_866', '679482418', 'pass8555', false);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 15', 'Texto 6', 'user20@example.com', 'user_814', '697608344', 'pass8212', true);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 32', 'Texto 16', 'user99@example.com', 'user_248', '668615839', 'pass8283', true);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 54', 'Texto 32', 'user57@example.com', 'user_975', '630453579', 'pass6078', false);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 3', 'Texto 6', 'user58@example.com', 'user_483', '696667331', 'pass7799', true);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 40', 'Texto 24', 'user18@example.com', 'user_110', '671518423', 'pass3937', false);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 93', 'Texto 54', 'user4@example.com', 'user_851', '691370028', 'pass5526', true);
INSERT INTO usuario (nombre, apellido, email, username, telefono, password, enabled) VALUES ('Nombre 24', 'Texto 53', 'user23@example.com', 'user_244', '693344297', 'pass2485', true);